codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%

ignore:
  - "target/**"
  - "tests/data/**"
  - "src/main.rs"
